services:
  bot:
    build:
      context: .
      args:
        TW_VERSION: "3"
    volumes:
      - ./.tw3-test:/etc/task
    environment:
      - DB_DATA=/etc/task/botdb
      - TW_TASKDATA=/etc/task/taskdata
      - TW_TASKRC=/etc/task/taskrc
    env_file:
      - .env
